DjangoApp/DjangoApp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static 
from django.conf import settings
from . import views 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
path('post/', include('posts.urls')),
path('users/', include('users.urls'))


] 
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT ) 

DjangoApp/posts/urls.py
from django.urls import path
from . import views 
app_name='posts'
urlpatterns = [
    path('', views.posts_list,name="list"),
    path('new-post/', views.post_new,name="new-post"),
    path('<slug:slug>', views.post_page,name="page"),


]

DjangoApp/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),

 
]

DjangoApp/posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

DjangoApp/users/models.py
from django.db import models

# Create your models here.

DjangoApp/posts/forms.py
from django import forms 
from . import models 

class CreatePost(forms.ModelForm): 
    class Meta: 
        model = models.Post
        fields = ['title','body','slug','banner']

DjangoApp/DjangoApp/views.py
#from django.http import HttpResponse 
from django.shortcuts import render
def homepage(request):
    #return HttpResponse("Hello, World! This is the homepage.")
    return render(request, 'home.html')

def about(request):
        #return HttpResponse("This is the about page.")
    return render(request, 'about.html')

DjangoApp/posts/views.py
from django.shortcuts import render,redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import  forms

# Create your views here.
def posts_list(request):
    # Retrieve all posts and order them by 'date' field in descending order.
    posts = Post.objects.all().order_by('-date')  # '-' indicates descending order
    return render(request, 'posts/posts_list.html', {'posts': posts})

# Correct indentation for post_page function
def post_page(request, slug):
    # Retrieve a single post using the slug
    post = Post.objects.get(slug=slug) 
    return render(request, 'posts/posts_page.html', {'post': post})

# Ensure the @login_required decorator and function are correctly indented
@login_required(login_url='/users/login/')
# def post_new(request):
#     return render(request, 'posts/posts_new.html')


def post_new(request):
    if request.method == 'POST': 
        form = forms.CreatePost(request.POST, request.FILES) 
        if form.is_valid():
            newpost = form.save(commit=False) 
            newpost.author = request.user 
            newpost.save()
            return redirect('posts:list')
    else:
        form = forms.CreatePost()
    return render(request, 'posts/post_new.html', { 'form': form })











    # if request.method == 'POST':
    #     form = PostForm(request.POST, request.FILES)  # Use request.FILES for image uploads
    #     if form.is_valid():
    #         form.save()
    #         return redirect('post_list')  # Redirect to the post list or any other view
    # else:
    #     form = PostForm()
    
    # return render(request, 'add_post.html', {'form': form})

DjangoApp/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout 

# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request,form.save())
            return redirect('posts:list')
    else:    
        form = UserCreationForm()
    
    return render(request, "users/register.html", {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:list")  # Make sure to indent correctly here
            return redirect("posts:list")  # Make sure to indent correctly here
    else:
        form = AuthenticationForm()

    return render(request, "users/login.html", {'form': form})
def logout_view(request):
    if request.method =="POST":
        logout(request)
        return redirect("users:login")

DjangoApp/posts/templates/posts/post_new.html
{% extends "layout.html" %}

{% block title %}
New Post page
{% endblock %}

{% block content %}
<section>
    
<h1>New Post Creation</h1>
<form class='form-with-validation' action="{%url 'posts:new-post'%}" method="post" enctype="multipart/form-data ">
     {% csrf_token %}
     {{ form}}
     <button class='form-submit'>Add post</button>
</form>

</section>
{% endblock %} 



{% comment %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post list</title>
</head>
<body>
    <h1>Hello world</h1>
</body>
</html>
{% endcomment %}

DjangoApp/posts/templates/posts/posts_list.html
{% extends "layout.html" %}
{% block title %}
Posts
{% endblock  %}

{% block content %}
<section>
<h1>Post</h1>

{% for post in posts   %}
<article class="post">

    <h2>
        {{post.title}} 
    </h2>

    <p>
        {{post.date}} 


    </p>
    <p>
        {{post.body}} 


    </p>
 
</article>



{% endfor %}
</section>
{% endblock %}


{% comment %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post list</title>
</head>
<body>
    <h1>Hello world</h1>
</body>
</html> {% endcomment %}

DjangoApp/posts/templates/posts/posts_page.html
{% extends "layout.html" %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
<section>
    <img class='banner' src="{{post.banner.url}}" alt="{{post.title}}">
    <h1>
        {{ post.title }}
    </h1>
    <p>{{ post.date }} by {{ post.author }}</p>

     <p>
        {{ post.body }}
    </p>
</section>
{% endblock %} 

{% comment %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post list</title>
</head>
<body>
    <h1>Hello world</h1>
</body>
</html>
{% endcomment %}

DjangoApp/templates/about.html
{% extends "layout.html" %}
{% block title %}
Home
{% endblock  %}

{% block content %}
<h1>
    Welcome to the Home Page
</h1>
<p>
    Checkout My <a href="/">Homepage </a>. 
</p>
{% endblock %}

DjangoApp/templates/home.html
{% extends "layout.html" %}
{% block title %}
Home
{% endblock  %}

{% block content %}
<h1>
    Welcome to the Home Page
</h1>
<p>
    Checkout My <a href="/about">About us </a>. 
</p>
{% endblock %}

DjangoApp/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
    {% block title %}
    Django App

    {%endblock%}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> 
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
<a href="/">Home</a>
<a href="/about">About</a>
<a href="{% url 'posts:list' %} ">Post</a>


{% if user.is_authenticated %}
<a href="{% url 'posts:new-post' %} ">New</a>

<form class="logout" action="{%url 'users:logout'%}" method="post">
{% csrf_token %}
<button class="logout-button">Logout</button>


</form>
 {%else%}
 <a href="{% url 'users:register' %} ">Register</a>
 <a href="{% url 'users:login' %} ">Login</a>
 {%endif%}


    </nav>
<main>
    {% block content %}
     
    {%endblock%}
</main>

</body>
</html>

DjangoApp/users/templates/users/login.html
{% extends "layout.html" %}
{% block title %}
User Login
{% endblock %}

{% block content %}
 <h1>User Login </h1>
<form class="form-with-validation " action="/users/login/" method="post">
    {% csrf_token %}
{{form}}
{% if request.GET.next%}
<input type="hidden" name="next" id="" value{{request.GET.next}}>
{% endif %}
<button class='form-submit'>Submit</button>



</form>
{% endblock %} 

DjangoApp/users/templates/users/register.html
{% extends "layout.html" %}
{% block title %}
Register a new User 
{% endblock %}

{% block content %}
 <h1>Register A New User </h1>
<form class="form-with-validation " action="/users/register/" method="post">
    {% csrf_token %}
{{form}}
<button class='form-submit'>Submit</button>



</form>
{% endblock %} 